- name: Wazuh Agent and Server Setup
  hosts: wazuh-client
  become: true
  tasks:
    - name: Copying script to client
      copy:
        src: ../scripts/wazuh-agent-setup.sh
        dest: /home/ubuntu/wazuh-agent-setup.sh
        mode: "0755"

    - name: Setting up Wazuh agent. Please wait ......
      shell: /home/ubuntu/wazuh-agent-setup.sh
      register: wazuh_agent_script_output
      async: 1200 # 20 minutes timeout
      poll: 0 # Non-blocking, allows other tasks to continue

    - name: Output of Wazuh agent setup
      async_status:
        jid: "{{ wazuh_agent_script_output.ansible_job_id }}"
      register: wazuh_agent_job_result
      until: wazuh_agent_job_result.finished
      retries: 120 # Retry 120 times (i.e., for up to 10 minutes)
      delay: 5 # Wait 5 seconds between retries

    - name: Formatted Output
      debug:
        msg:
          - "STDOUT: {{ wazuh_agent_job_result.stdout | regex_replace('\\x1b\\[[0-9;]*m', '') | default('No stdout available') }}"
          - "STDERR: {{ wazuh_agent_job_result.stderr | regex_replace('\\x1b\\[[0-9;]*m', '') | default('No stderr available') }}"

    - name: Removing script from client
      file:
        path: /home/ubuntu/wazuh-agent-setup.sh
        state: absent

- name: Wazuh Server Setup
  hosts: wazuh-server
  become: true
  tasks:
    - name: Copying script to server
      copy:
        src: ../scripts/wazuh-server-setup.sh
        dest: /home/ubuntu/wazuh-server-setup.sh
        mode: "0755"

    - name: Setting up Wazuh server. Please wait ......
      shell: /home/ubuntu/wazuh-server-setup.sh
      register: wazuh_server_script_output
      async: 1200 # 20 minutes timeout
      poll: 0 # Non-blocking, allows other tasks to continue

    - name: Output of Wazuh server setup
      async_status:
        jid: "{{ wazuh_server_script_output.ansible_job_id }}"
      register: wazuh_server_job_result
      until: wazuh_server_job_result.finished
      retries: 120 # Retry 120 times (i.e., for up to 10 minutes)
      delay: 5 # Wait 5 seconds between retries

    - name: Formatted Output
      debug:
        msg:
          - "STDOUT: {{ wazuh_server_job_result.stdout | regex_replace('\\x1b\\[[0-9;]*m', '') | default('No stdout available') }}"
          - "STDERR: {{ wazuh_server_job_result.stderr | regex_replace('\\x1b\\[[0-9;]*m', '') | default('No stderr available') }}"

    - name: Removing script from server
      file:
        path: /home/ubuntu/wazuh-server-setup.sh
        state: absent
